config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/home', to: 'welcome#home'

  resources :recipes do
    resources :reviews, only: [:create]
    member do
      post 'like'
    end
  end


  resources :chefs, except: [:new, :destroy]

  get '/register', to: 'chefs#new'

  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]



end

app/models/chef.rb
class Chef < ActiveRecord::Base
	#model relationships
	has_many :recipes
	has_many :reviews
	has_many :likes

	#user validations
	before_save { self.email = email.downcase}
	validates :name, presence: true, length: {minimum: 3, maximum: 40}
	VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 105 },
	uniqueness: { case_sensitive: false },
	format: {with: VALID_EMAIL_REGEX }

	has_secure_password



end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
	before_action :set_chef, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update]

	#index with paginatation feature, allows to organize the collection better.
	def index
		@chefs = Chef.paginate(page: params[:page], per_page: 3)
	end

	#chefs variable equals to a new chef
	def new
		@chefs = Chef.new
	end

	#chefs creates the entry based on private params method.
	def create
		@chefs = Chef.new(chefs_params)
		if @chefs.save
			flash[:success] = "Your account was created successfully"
			session[:chef] = @chefs.id
			redirect_to recipes_path
		else
			render 'new'
		end
	end

	def edit
	end

	#updates if only the params are passed
	def update
		if @chefs.update(chefs_params)
			flash[:success] = "Your changes to the account was saved successfully"
			redirect_to chef_path(@chefs)
		else
			render 'edit'
		end
	end

	#shows the recipes made by the chef
	def show
		@recipes = @chefs.recipes.paginate(page: params[:page], per_page: 3)
	end


	private

	#params a method parameter that takes variavle number of aruguments/ works for HTTP requests.
	def chefs_params
		params.require(:chef).permit(:name, :email, :password)
	end


	#this private method checks if the current user of the session is the same as the chef that being edited.
	def require_same_user
		if current_user = @chef
			flash[:danger] = "You can only edit your own profile"
			redirect_to root_path
		end
	end

	#a method used in before_action in order to keep the code DRY
	def set_chef
		@chefs = Chef.find(params[:id])
	end
end

app/views/chefs/_form.html.erb
<!--render a partial used for displaying error messages-->
<% render 'shared/errors', obj: @chefs %>

<!--form_for chefs-->
<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for @chefs do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %><br/>

		<%= f.label :email %>
		<%= f.text_field :email %><br/>

		<%= f.label :password %>
		<%= f.password_field :password %><br/>

		<!--due to the form being used in new.html and edit.html this code is needed-->
		<%= f.submit(@chefs.new_record? ? 'Create Account' : 'Save Changes' , class: 'btn btn-success') %>

		<% end %>
	</div>
</div>

app/views/chefs/edit.html.erb
<!--renders a partial used for displaying the title -->
<%= render 'shared/page_title', title: 'Edit your Account' %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "All Chefs" %>

<!--tabs sections to switch between chefs#index and recipes#index-->
<ul class="nav nav-tabs">
	<li class="active">
		<%= link_to "Chefs", chefs_path %>
	</li>
	<li>
		<%= link_to "Recipes", recipes_path %>
	</li>
</ul>

<!--pagination feature-->
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= will_paginate %>
	</div>
</div>

<!--to display each chef in the database-->
<% @chefs.each do |chef| %>
<div class='row'>
	<div class=" col-md-4 col-md-offset-4 center">
		<section class="chef_info center">
			<%= link_to gravatar_for(chef, size: 225), chef_path(chef) %>
			<h5>Chef name: <%= chef.name %></h5>
		</section>

	</div>
</div>

<% end %>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: 'Create an account' %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef " + @chefs.name %>


<div class="row">
	<div class=" col-md-4 col-md-offset-4 center">
		<%= gravatar_for @chefs, size: 200 %>
	</div>
</div>

<!--shows the user's created recipes-->
<div class="col-md-4 col-md-offset-4 center"> 
	<br>
	<h3>Recipes :</h3>
	<%= will_paginate @recipes %>
	<% @recipes.each do |recipe| %>
</div>
<div class="row">
	<div class="col-md-6 well col-lg-offset-3">
		<h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
		<p><%= recipe.summary %></p>
		<p>
			<span class="quiet"><small> created: <%= time_ago_in_words(recipe.created_at)  %> ago,</small></span>
			<span class="quiet"><small> updated: <%= time_ago_in_words(recipe.updated_at)%> ago </small></span>
		</p>
		<div class="pull-right">
			<%= link_to like_recipe_path(recipe, like: true), method: :post do %>
			<i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
			<% end %> &nbsp&nbsp&nbsp&nbsp
			<%= link_to like_recipe_path(recipe, like: false), method: :post do %>
			<i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
			<% end %>
		</div>
	</div>
	<% end %>


	<!--sends the user to their edit page-->
	<div class="col-md-4 col-md-offset-3 center">
		<%= link_to "Edit your Account", edit_chef_path(@chefs), class: "btn btn-success pull right" %>
	</div>

	<div class="col-md-4 col-md-offset-3 center">
		<h5><%= link_to 'Return to Return Listing', recipes_path, class: "btn btn-small btn-success" %></h5>
	</div>
</div>
</div>