config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/home', to: 'welcome#home'

  resources :recipes do
    resources :reviews, only: [:create]
    member do
      post 'like'
    end
  end


  resources :chefs, except: [:new, :destroy]

  get '/register', to: 'chefs#new'

  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]



end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

	#model relationships and validations
	belongs_to :chef
	has_many :likes, dependent: :destroy
	has_many :recipe_styles, dependent: :destroy
	has_many :styles, through: :recipe_styles
	has_many :recipe_ingredients, dependent: :destroy
	has_many :ingredients, through: :recipe_ingredients
	has_many :reviews, dependent: :destroy
	validates :chef_id, presence: true
	validates :name, presence: true, length: { minimum: 5, maximum: 100}
	validates :summary, presence: true, length: {minimum: 10, maximum: 150}
	validates :description, presence: true, length: {minimum: 20, maximum: 500}
	mount_uploader :picture, PictureUploader
	validate :picture_size

	#sorts the the order of the recipes collection in descending order
	default_scope -> { order(updated_at: :desc) }

	#like thumbs up feature
	def thumbs_up_total
		self.likes.where(like: true).size
	end

	#like thumbs down feature
	def thumbs_down_total
		self.likes.where(like: false).size
	end

	#private method for images making sure the picture size doesn't go overboard
	private
	def picture_size
		if picture.size > 5.megabytes
			errors.add(:picture, "should be less than 5MB")
		end
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :set_recipe_find, only: [:edit, :update, :show, :like]
	before_action :require_user_like, only: [:like]
	before_action :admin_to_recipes, only: [:destroy]
	before_action :require_same_user_to_recipes, expect: [:show, :index, :like]
	before_action :require_same_user_to_recipes, only: [:edit, :update]

	#basic crud commands, refer to chefs_controller for further details
	def index
		@recipes = Recipe.paginate(page: params[:page], per_page: 4)
	end

	def show
		@review = Review.new(params[:body])
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.chef = current_user

		if @recipe.save
			flash[:success] = "Your recipe was created successfully!"
			redirect_to recipes_path
		else
			render :new

		end
	end

	def edit
		
	end

	def update
		
		if @recipe.update(recipe_params)
			flash[:success] = "Your recipe was updated successfully!"
			redirect_to recipes_path
		else
			render :edit
		end
	end

	def new
		@recipe = Recipe.new
	end


	# a like feature mainly used the recipes#index and recipes#show
	def like
		like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
		if like.valid?
			flash[:success] = "Your selection was successful"
			redirect_to :back
		else
			flash[:danger] = "You can only like/dislike a recipe once"
			redirect_to :back
		end
	end

	def destroy
		
		@recipe = Recipe.find(params[:id]).destroy
		if @recipe.destory
			flash[:success] = "The Recipe was deleted successfully"
			redirect_to recipes_path
		else
			flash[:error] = "There was an issue, please try again"
			redirect_to recipes_path
		end
	end

	private

	def recipe_params
		params.require(:recipe).permit(:name, :summary, :description, :picure, style_ids: [], ingredient_ids: [])
	end

			#this error will flash if the current user does not equal the owner of the current recipe and if they're not an admin.
			def require_same_user_to_recipes
				if current_user != @recipe.chef and !current_user.admin?
					flash[:danger] = "You can only edit/update your own recipes"
					redirect_to root_path
				end
			end

			#before action method to keep the code DRY
			def set_recipe_find
				@recipe = Recipe.find(params[:id])	
			end

			#redirects to recipes#index if the current user isn't an admin
			def admin_to_recipes
				redirect_to recipes_path unless current_user.admin?
			end

			#if not loggin in, then this error will flash
			def require_user_like
				if !logged_in?
					flash[:danger] = "You must be logged in"
					redirect_to :back
				end
			end
		end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<!--the form for creating a recipe to the db-->
<div class="row">
	<div class="well col-md-8 col-md-offset-2">

		<!--multipart if used for Avatar upload -->
		<%= form_for(@recipe, html: { multipart: true}) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %><br/>

		<%= f.label :summary %>
		<%= f.text_field :summary %><br/>

		<%= f.label :description %>
		<%= f.text_area :description, rows: 10 %><br/>


		<!--checkboxes to associate the styles and ingredient to the recipe being created-->
		<strong>Styles: </strong>
		<%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
		<% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
		<% end %>
		<br><br>
		
		<strong>Ingredients: </strong>
		<%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbi| %>
		<% cbi.label(class: "checkbox-inline input_checkbox") {cbi.check_box(class: "checkbox") + cbi.text} %>
		<% end %>
		<br><br>

		<!--image uploading(work in progress)-->
		<span class='picture'>
			<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>

			<%= f.submit(@recipe.new_record? ? "Create Recipe" : 'Edit Recipe', class: "btn btn-md btn-success") %>
			<% end %>
		</div>
	</div>

	<!--javascript code to alert the user to provide a smaller image-->
	<script type="text/javascript">
	$('#recipe_picture').bind('change', function() {
		size_in_megabytes = this.files[0].size/1024/1024;
		if (size_in_megabytes > 5) {
			alert('Maximum file size is 5MB. Please choose a smaller file');
		}
	});
	</script>

app/views/recipes/_styles.html.erb
<!--render partial for styles-->
<span class="quiet"><small> created: <%= time_ago_in_words(recipe.created_at)  %> ago,</small></span>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<!--tabs section to navigate between recipes#index and chefs#index-->
<ul class="nav nav-tabs">
	<li class="active">
		<%= link_to "Recipes", recipes_path %>
	</li>
	<li>
		<%= link_to "Chefs", chefs_path %>
	</li>
</ul>

<br>

<!--if not logged in displays this message-->
<% if !logged_in? %>
<p> <%= link_to "Log in", login_path %> or <%= link_to "create an account", register_path %> to create a recipe! </p>
<% end %>

<%= will_paginate %>

<!--shows every recipe in the db along with sorting the collection with pagination-->
<br><br>
<% @recipes.each do |recipe| %>
<div class = "row">
	<div class = "col-md-2">
		<section class="chef_info center">
			<%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
			<h5>Chef name: <%= recipe.chef.name %></h5>
		</section>
	</div>

	<div class="col-md-6 well">
		<h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
		<p><%= recipe.summary %></p>
		<% if recipe.styles.any? %>
		<p> Style: <%= render recipe.styles %></p>
		<% end %>
		<% if recipe.ingredients.any? %>
		<p>Ingredients: <%= render recipe.ingredients %></p>
		<% end %>
		<p>
			<span class="quiet"><small> created: <%= time_ago_in_words(recipe.created_at)  %> ago,</small></span>
			<span class="quiet"><small> updated: <%= time_ago_in_words(recipe.updated_at)%> ago </small></span>
		</p>
		<div class='col-md-4'>
			<%= image_tag(recipe.picure.url, size: "250x150", class: "gravatar") if recipe.picture? %>
		</div>
	</div>
</div>
<hr/>
<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<!--shows the requested recipe to the user-->
<div class="row">
	<div class="col-md-4 pull-right center">
		<%= link_to gravatar_for(@recipe.chef, size: 200), chef_path(@recipe.chef) %>
		<p>
			<h4>Brought to you by : <%= @recipe.chef.name %></h4>
		</p>
	</div>
	<div class="col-md-8">

		<% if logged_in? and (@recipe.chef == current_user || current_user.admin?) %>
		<%= link_to "Delete Recipe", @recipe , method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-success pull right" %>
		<% end %>

		<% if logged_in? and (@recipe.chef == current_user || current_user.admin?) %>
		<%= link_to "Edit this Recipe", edit_recipe_path(@recipe), class: "btn btn-success pull right" %>
		<% end %>


		<h2><%= @recipe.summary %></h2>
		<div class="show_recipe">
			<%= image_tag(@recipe.picture, class: "gravatar") %>
		</div>
		<div class="well">
			<% if @recipe.styles.any? %>
			<p> Style: <%= render @recipe.styles %></p>
			<% end %>

			<% if @recipe.ingredients.any? %>
			<p>Ingredients: <%= render @recipe.ingredients %></p>
			<% end %>
			<p>
				<strong>Steps:</strong>
			</p>
			<%= simple_format(@recipe.description) %>
		</div>
	</div>
</div>
<div class = "pullright">
	<span class="quiet"><small> created: <%= time_ago_in_words(@recipe.created_at)  %> ago,</small></span>
	<span class="quiet"><small> updated: <%= time_ago_in_words(@recipe.updated_at)%> ago </small></span>
</div>

<!--displays the review(work in progress)-->
<div class ="row">
	<br>
	<h4 class= "review-heading"> Reviews </h4>
	<hr>
	<div class = 'col-md-12'>
		<div class='js-reviews'>
			<%= render 'reviews/review'%>
		</div>
	</div>
</div>

<!--creates a new review-->
<% if logged_in? %>
<div class='new-review'>
	<%= render 'reviews/form', recipe: @recipe, review: @review %>
</div>
<% else %>
<p> <%= link_to "Log in", login_path %> or <%= link_to "create an account", register_path %> to create a comment! </p>
<% end %>


<h5><%= link_to 'Return to Return Listing', recipes_path || :back, class: "btn btn-small btn-success" %></h5>