config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'

  get '/home', to: 'welcome#home'

  resources :recipes do
    resources :reviews, only: [:create]
    member do
      post 'like'
    end
  end


  resources :chefs, except: [:new, :destroy]

  get '/register', to: 'chefs#new'

  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]



end

app/views/layouts/_footer.html.erb
<!--a partial for displaying the footer message on every page and keeping the code DRY-->

<div class="footer">
	<br>
	<p>&copy; MyRecipes 2016</p>
</div>

app/views/layouts/_messages.html.erb
<!-- a errors messages to be used in several other files and created to keep the code DRY-->
<div class="row">
	<div class='col-md-10'>
		<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>">
			<%= message %>
			<a class="close" data-dismiss="alert">&#215</a>
		</div>
		<% end %>
	</div>

</div>

app/views/layouts/_navigation.html.erb
<!--the black navigation bar on top-->
<header class="navbar navbar-fixed-top navbar-default">
	<div class="container">
		<%= link_to "myRecipes", root_path , class: "btn btn-default btn-primary", id: "logo" %>
		<ul class="nav_ul_item">
			<li class="dropdown">
				<%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
				Styles <b class="caret"></b>
				<% end %>
				<ul class='dropdown-menu'>
					<% Style.all.each do |style| %>
					<li><%= link_to style.name, style_path(style) %></li>
					<% end %>
					<% if logged_in? %>
					<li class="divider"></li>
					<li>
						<%= link_to(new_style_path) do %>
						New Style
						<% end %>
					</li>
					
					<% end %>
				</ul>
			</li>
		</ul>

		<ul class="nav_ul_item">
			<li class="dropdown">
				<%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
				Ingredients <b class="caret"></b>
				<% end %>
				<ul class='dropdown-menu'>
					<% Ingredient.all.each do |ingredient| %>
					<li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
					<% end %>
					<% if logged_in? %>
					<li class="divider"></li>
					<li>
						<%= link_to(new_ingredient_path) do %>
						New Ingredient
						<% end %>
					</li>
					<% end %>
				</ul>
			</li>
		</ul>
		<% if logged_in? %>
		<div class="nav_item">
			<%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-warning" %>
		</div>
		<ul class="nav_ul_item">
			<li class="dropdown">
				<%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
				<%= current_user.name %> <b class="caret"></b>
				<% end %>
				<ul class='dropdown-menu'>
					<li><%= link_to "View Profile", chef_path(current_user) %></li>
					<li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
					<li class="divider"></li>
					<li><%= link_to "Logout", logout_path %></li>
				</ul>
			</li>
		</ul>
		<% else %>
		<div class="nav_item">
			<%= link_to "Log in", login_path, class: "btn btn-default btn-success" %>
		</div>
		<% end %>
	</div>
</header>

app/views/layouts/application.html.erb
<!--to declare what html version the project is using-->
<!DOCTYPE html>

<html>
<head>
	<!--title displayed on the tabs-->
	<title>MyRecipes</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
	<div class="container">
		<%= render 'layouts/messages' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</body>
	</html>